languageCode = "en-us"
title = "Muninn"
baseurl = "https://tech.crandom.com/"
theme = "slim"

[params]
  Subtitle = "Life is short, I use python. Winter is comming, Let's go!"
  GithubID = "hyacinthus"
  # AnalyticsID = "Your Google Analytics tracking code"
  DisqusShortname = "crandom"
  Summary = false # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "Copyright Muninn 2021. Powered by Hugo. <a href='https://beian.miit.gov.cn'>陕ICP备16007985号-2</a>"
