baseURL = "https://tech.crandom.com/"
title = "何枝可依"
languageCode = "en-us"
paginate = 10

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  env = "production"
  description = "Life is short, I use python. Winter is comming, Let's go!"
  author = "Muninn"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  ShowToc = true
  disqusShortname = "crandom"
  defaultTheme = "auto"

  [params.homeInfoParams]
    Title = "何枝可依"
    Content = "Life is short, I use python. Winter is comming, Let's go!"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hyacinthus"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/summery"

[params.assets]
  disableHLJS = true

ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Archive"
  url = "/archives/"
  weight = 5

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 15

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]
